### PR TITLE
Major changes

### LINKED ISSUE #66: Replace cTracer with cLineBlockTracer
As of cuberite/cuberite#3704, `cTracer` is obsolete. Replace it with `cLineBlockTracer`.

### PR DESCRIPTION
**Pull request by mathiascode**
Changes:
- Replaced tracer
- Global variables to local whenever possible
- Removed unused variables
- Added /god command
- Updated descriptions
- Can change mob heads to any players' head
- Additional fixes and tweaks

Fixes #66, #43 

All the commands worked properly when testing.

### CODE REVIEW

**Comment by Seadragon91** [comment]
In `general.lua` lines 98-100 you have the 3 positions as variables defined, but you have ``GetPosX / GetPosY / GetPosZ` in the code below.

Variables that can be removed in files:
```
jails.lua:51:8: unused variable 'Server'
jails.lua:82:8: unused variable 'Server'
warps.lua:21:8: unused variable 'Server'
warps.lua:52:8: unused variable 'Server'
```

**Comment by mathiascode** [comment]
Thanks for the link! It's so easy to forget changing some things in situations like these, so the tool seems really nice. :)

**Comment by Seadragon91** [comment]
If you want to use it run it with `luacheck -a -g .`
The param `-a` ignores unused function arguments and the param `-g` ignores global variables. Without this two flags, the output would contain to many warnings.

**Comment by Seadragon91** [comment]
Have created the config file `.luacheckrc`. It contains the options and the globals (function, constants, block types, etc) from cuberite. 

Documentation: http://luacheck.readthedocs.io/en/stable/config.html
My `.luacheckrc` file: https://gist.github.com/Seadragon91/5560cefb67d8cf412934833bea646655

Now that it contains the globals, it shows a few more warnings. Some of them can be ignored.

**Comment by tonibm19** [comment]
Seems OK to me.
If there are no objections I'll merge.

**Comment by Seadragon91** [comment]
@tonibm19 There are still a few problems that should be fixed.
Example:
[hooks.lua#L16](https://github.com/mathiascode/Essentials/blob/ccd52b24fec3ba91bb3312c476ddc322d6c0d885/hooks.lua#L16)
There is a undefined variable named `BlockType` and the block type `E_BLOCK_SIGN` does not exists, correct would be `E_BLOCK_SIGN_POST` and / or `E_BLOCK_WALLSIGN`

**Comment by mathiascode** [comment]
I will finish this some day, but closing for now.

**Comment by mathiascode** [comment]
This PR is ready now.

**Comment by Seadragon91** [comment]
Ah sorry, with the newest changes boats have now a [material](https://api.cuberite.org/cBoat.html#eMaterial) param and it's not optional.

**Comment by mathiascode** [comment]
I guess you wanted to comment on this PR? https://github.com/cuberite/Core/pull/190

**Pull request merged**
